### ISSUE TITLE
Name within HACS

### ISSUE THREAD

**Issue by houtknots** [JuanMTech/green_dark_mode#1]
The name of the theme within HACS is Amoled Blue

![image](https://user-images.githubusercontent.com/31192098/73139658-86c82580-4070-11ea-8cb0-32130cd49b34.png)

**Comment by JuanMTech** [comment]
I just noticed that. Also on the Green Light mode theme. Not sure why. Everything is correct on the hacs.json file for both themes. Maybe @ludeeus can check on that.

**Comment by ludeeus** [comment]
> Everything is correct on the hacs.json file for both themes.

_Not really ;) https://github.com/JuanMTech/green_dark_mode/blob/v1.0/hacs.json_

HACS uses the content in the releases, not master.
When you release a new version it will be OK.

**Comment by JuanMTech** [comment]
So that's where the issue was. Oops! Fixed it. Thanks @ludeeus
